#!/usr/bin/env bash

## #ddev-generated
## Description: export MariaDB schema
## Usage: maria-schema [flags] [args]
## Example: "ddev maria-schema"
## DBTypes: mariadb
## ExecRaw: true

ddev exec 'mariadb-dump --no-data --skip-comments --skip-set-charset db' \
  | sed -E '/^\/\*!/d;/^\/\*M!/d;/^(LOCK TABLES|UNLOCK TABLES|COMMIT;|SET )/d' \
  > db.sql
